# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resources\camerawindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraWindow(object):
    def setupUi(self, CameraWindow):
        CameraWindow.setObjectName("CameraWindow")
        CameraWindow.resize(753, 801)
        self.centralwidget = QtWidgets.QWidget(CameraWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Create main vertical splitter
        self.main_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.main_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.main_splitter.setObjectName("main_splitter")
        self.main_splitter.setHandleWidth(5)
        # Create view area widget
        self.view_area = QtWidgets.QWidget(self.main_splitter)
        self.view_area.setObjectName("view_area")
        self.view_layout = QtWidgets.QGridLayout(self.view_area)
        self.view_layout.setObjectName("view_layout")
        
        # Create control area widget
        self.control_area = QtWidgets.QWidget(self.main_splitter)
        self.control_area.setObjectName("control_area")
        self.control_layout = QtWidgets.QGridLayout(self.control_area)
        self.control_layout.setObjectName("control_layout")
        
        # Add widgets to main splitter
        self.main_splitter.addWidget(self.view_area)
        self.main_splitter.addWidget(self.control_area)
        
        # Set up view area (top part)
        self.view_stackedWidget = QtWidgets.QStackedWidget(self.view_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.view_stackedWidget.sizePolicy().hasHeightForWidth())
        self.view_stackedWidget.setSizePolicy(sizePolicy)
        self.view_stackedWidget.setObjectName("view_stackedWidget")
        self.imageview_page = QtWidgets.QWidget()
        self.imageview_page.setObjectName("imageview_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.imageview_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.videovieweditor = ImageViewEditor(self.imageview_page)
        self.videovieweditor.setObjectName("videovieweditor")
        self.gridLayout_2.addWidget(self.videovieweditor, 0, 0, 1, 1)
        self.view_stackedWidget.addWidget(self.imageview_page)
        self.absorption_view_page = QtWidgets.QWidget()
        self.absorption_view_page.setObjectName("absorption_view_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.absorption_view_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.absorption_view_widget = AbsorptionViewWidget(self.absorption_view_page)
        self.absorption_view_widget.setObjectName("absorption_view_widget")
        self.gridLayout_3.addWidget(self.absorption_view_widget, 0, 2, 1, 1)
        self.view_stackedWidget.addWidget(self.absorption_view_page)
        self.fluorescence_view_page = QtWidgets.QWidget()
        self.fluorescence_view_page.setObjectName("fluorescence_view_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.fluorescence_view_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fluorescence_view_widget = FluorescenceViewWidget(self.fluorescence_view_page)
        self.fluorescence_view_widget.setObjectName("fluorescence_view_widget")
        self.gridLayout_6.addWidget(self.fluorescence_view_widget, 0, 0, 1, 1)
        self.view_stackedWidget.addWidget(self.fluorescence_view_page)
        self.multishot_view_page = QtWidgets.QWidget()
        self.multishot_view_page.setObjectName("multishot_view_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.multishot_view_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        # Create tab widget for multishot views
        self.multishot_tab_widget = QtWidgets.QTabWidget(self.multishot_view_page)
        self.multishot_tab_widget.setObjectName("multishot_tab_widget")
        
        # Tabbed view tab
        self.tabbed_view_tab = QtWidgets.QWidget()
        self.tabbed_view_tab.setObjectName("tabbed_view_tab")
        self.tabbed_view_layout = QtWidgets.QGridLayout(self.tabbed_view_tab)
        self.multishot_view_widget = MultishotViewWidget(self.tabbed_view_tab)
        self.multishot_view_widget.setObjectName("multishot_view_widget")
        self.tabbed_view_layout.addWidget(self.multishot_view_widget, 0, 0, 1, 1)
        self.multishot_tab_widget.addTab(self.tabbed_view_tab, "Tabbed View")
        
        # Vertical view tab
        self.vertical_view_tab = QtWidgets.QWidget()
        self.vertical_view_tab.setObjectName("vertical_view_tab")
        self.vertical_view_layout = QtWidgets.QGridLayout(self.vertical_view_tab)
        self.multishot_vertical_view_widget = MultishotVerticalViewWidget(self.vertical_view_tab)
        self.multishot_vertical_view_widget.setObjectName("multishot_vertical_view_widget")
        self.vertical_view_layout.addWidget(self.multishot_vertical_view_widget, 0, 0, 1, 1)
        self.multishot_tab_widget.addTab(self.vertical_view_tab, "Vertical View")
        
        # 1013 LS view tab
        self.view_1013ls_tab = QtWidgets.QWidget()
        self.view_1013ls_tab.setObjectName("view_1013ls_tab")
        self.view_1013ls_layout = QtWidgets.QGridLayout(self.view_1013ls_tab)
        self.multishot_1013ls_view_widget = Multishot1013LSViewWidget(self.view_1013ls_tab)
        self.multishot_1013ls_view_widget.setObjectName("multishot_1013ls_view_widget")
        self.view_1013ls_layout.addWidget(self.multishot_1013ls_view_widget, 0, 0, 1, 1)
        self.multishot_tab_widget.addTab(self.view_1013ls_tab, "1013 LS")
        
        self.gridLayout_4.addWidget(self.multishot_tab_widget, 0, 0, 1, 1)
        self.view_stackedWidget.addWidget(self.multishot_view_page)
        self.view_layout.addWidget(self.view_stackedWidget, 0, 0, 1, 1)
        
        # Set up control area (bottom part)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.camera_control_widget = CameraControlWidget(self.control_area)
        self.camera_control_widget.setObjectName("camera_control_widget")
        self.horizontalLayout_3.addWidget(self.camera_control_widget)
        self.imagecapturemodewidget = ImageCaptureModeWidget(self.control_area)
        self.imagecapturemodewidget.setObjectName("imagecapturemodewidget")
        self.horizontalLayout_3.addWidget(self.imagecapturemodewidget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roi_analyzer_widget = RoiIntegrationAnalyzer(self.control_area)
        self.roi_analyzer_widget.setObjectName("roi_analyzer_widget")
        self.horizontalLayout_2.addWidget(self.roi_analyzer_widget)
        self.gaussian2d_analyzer_widget = GaussianFitAnalyzer(self.control_area)
        self.gaussian2d_analyzer_widget.setObjectName("gaussian2d_analyzer_widget")
        self.horizontalLayout_2.addWidget(self.gaussian2d_analyzer_widget)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.savebox_verticalLayout = QtWidgets.QVBoxLayout()
        self.savebox_verticalLayout.setObjectName("savebox_verticalLayout")
        self.savebox_widget = SaveBoxWidget(self.control_area)
        self.savebox_widget.setObjectName("savebox_widget")
        self.savebox_verticalLayout.addWidget(self.savebox_widget)
        self.horizontalLayout.addLayout(self.savebox_verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.control_layout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        
        # Set up main layout
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.addWidget(self.main_splitter)
        CameraWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CameraWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 26))
        self.menubar.setObjectName("menubar")
        CameraWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CameraWindow)
        self.statusbar.setObjectName("statusbar")
        CameraWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CameraWindow)
        self.view_stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(CameraWindow)

    def retranslateUi(self, CameraWindow):
        _translate = QtCore.QCoreApplication.translate
        CameraWindow.setWindowTitle(_translate("CameraWindow", "J(jt)kam"))

from package.analyzers.gaussianfitanalyzer import GaussianFitAnalyzer
from package.analyzers.roiintegrationanalyzer import RoiIntegrationAnalyzer
from package.widgets.absorption_view_widget import AbsorptionViewWidget
from package.widgets.cameracontrolwidget import CameraControlWidget
from package.widgets.fluorescence_view_widget import FluorescenceViewWidget
from package.widgets.imagecapturemodewidget import ImageCaptureModeWidget
from package.widgets.imagevieweditor import ImageViewEditor
from package.widgets.multishot_view_widget import MultishotViewWidget
from package.widgets.multishot_vertical_view_widget import MultishotVerticalViewWidget
from package.widgets.multishot_1013ls_view_widget import Multishot1013LSViewWidget
from package.widgets.saveboxwidget_edited_v1 import SaveBoxWidget
# from package.widgets.saveboxwidget_edited import SaveBoxWidget



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraWindow = QtWidgets.QMainWindow()
    ui = Ui_CameraWindow()
    ui.setupUi(CameraWindow)
    CameraWindow.show()
    sys.exit(app.exec_())
