# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resources\fluorescence_view_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FluorescenceViewWidget(object):
    def setupUi(self, FluorescenceViewWidget):
        FluorescenceViewWidget.setObjectName("FluorescenceViewWidget")
        FluorescenceViewWidget.resize(609, 471)
        self.gridLayout = QtWidgets.QGridLayout(FluorescenceViewWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(FluorescenceViewWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.N_tab = QtWidgets.QWidget()
        self.N_tab.setObjectName("N_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.N_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.N_view_editor = ImageViewEditor(self.N_tab)
        self.N_view_editor.setObjectName("N_view_editor")
        self.gridLayout_2.addWidget(self.N_view_editor, 0, 0, 1, 1)
        self.tabWidget.addTab(self.N_tab, "")
        self.diff_tab = QtWidgets.QWidget()
        self.diff_tab.setObjectName("diff_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.diff_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.diff_view_editor = ImageViewEditor(self.diff_tab)
        self.diff_view_editor.setObjectName("diff_view_editor")
        self.gridLayout_3.addWidget(self.diff_view_editor, 0, 0, 1, 1)
        self.tabWidget.addTab(self.diff_tab, "")
        self.atom_tab = QtWidgets.QWidget()
        self.atom_tab.setObjectName("atom_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.atom_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.atom_view_editor = ImageViewEditor(self.atom_tab)
        self.atom_view_editor.setObjectName("atom_view_editor")
        self.gridLayout_4.addWidget(self.atom_view_editor, 0, 0, 1, 1)
        self.tabWidget.addTab(self.atom_tab, "")
        self.reference_tab = QtWidgets.QWidget()
        self.reference_tab.setObjectName("reference_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.reference_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.reference_view_editor = ImageViewEditor(self.reference_tab)
        self.reference_view_editor.setObjectName("reference_view_editor")
        self.gridLayout_6.addWidget(self.reference_view_editor, 0, 0, 1, 1)
        self.tabWidget.addTab(self.reference_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FluorescenceViewWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FluorescenceViewWidget)

    def retranslateUi(self, FluorescenceViewWidget):
        _translate = QtCore.QCoreApplication.translate
        FluorescenceViewWidget.setWindowTitle(_translate("FluorescenceViewWidget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.N_tab), _translate("FluorescenceViewWidget", "Atom Number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diff_tab), _translate("FluorescenceViewWidget", "Difference Counts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atom_tab), _translate("FluorescenceViewWidget", "With Atoms Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reference_tab), _translate("FluorescenceViewWidget", "Reference Image"))
from package.widgets.imagevieweditor import ImageViewEditor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FluorescenceViewWidget = QtWidgets.QWidget()
    ui = Ui_FluorescenceViewWidget()
    ui.setupUi(FluorescenceViewWidget)
    FluorescenceViewWidget.show()
    sys.exit(app.exec_())
