# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resources\gaussianfitanalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GaussianFitAnalyzer(object):
    def setupUi(self, GaussianFitAnalyzer):
        GaussianFitAnalyzer.setObjectName("GaussianFitAnalyzer")
        GaussianFitAnalyzer.resize(206, 104)
        self.gridLayout = QtWidgets.QGridLayout(GaussianFitAnalyzer)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(GaussianFitAnalyzer)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.enable_checkBox = QtWidgets.QCheckBox(self.frame)
        self.enable_checkBox.setObjectName("enable_checkBox")
        self.verticalLayout.addWidget(self.enable_checkBox)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(GaussianFitAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(GaussianFitAnalyzer)

    def retranslateUi(self, GaussianFitAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        GaussianFitAnalyzer.setWindowTitle(_translate("GaussianFitAnalyzer", "Form"))
        self.label.setText(_translate("GaussianFitAnalyzer", "Gaussian Fit Analyzer"))
        self.enable_checkBox.setText(_translate("GaussianFitAnalyzer", "Enable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GaussianFitAnalyzer = QtWidgets.QWidget()
    ui = Ui_GaussianFitAnalyzer()
    ui.setupUi(GaussianFitAnalyzer)
    GaussianFitAnalyzer.show()
    sys.exit(app.exec_())
