# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resources\plothistorywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotHistoryWindow(object):
    def setupUi(self, PlotHistoryWindow):
        PlotHistoryWindow.setObjectName("PlotHistoryWindow")
        PlotHistoryWindow.resize(350, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PlotHistoryWindow.sizePolicy().hasHeightForWidth())
        PlotHistoryWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(PlotHistoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.set_min_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.set_min_pushButton.setObjectName("set_min_pushButton")
        self.gridLayout.addWidget(self.set_min_pushButton, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.clear_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 3, 3, 1, 1)
        self.history_PlotWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.history_PlotWidget.sizePolicy().hasHeightForWidth())
        self.history_PlotWidget.setSizePolicy(sizePolicy)
        self.history_PlotWidget.setObjectName("history_PlotWidget")
        self.gridLayout.addWidget(self.history_PlotWidget, 2, 0, 1, 4)
        self.set_max_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.set_max_pushButton.setObjectName("set_max_pushButton")
        self.gridLayout.addWidget(self.set_max_pushButton, 3, 1, 1, 1)
        self.data_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.data_label.setFont(font)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 1, 0, 1, 1)
        PlotHistoryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotHistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        PlotHistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotHistoryWindow)
        self.statusbar.setObjectName("statusbar")
        PlotHistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotHistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotHistoryWindow)

    def retranslateUi(self, PlotHistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotHistoryWindow.setWindowTitle(_translate("PlotHistoryWindow", "MainWindow"))
        self.set_min_pushButton.setText(_translate("PlotHistoryWindow", "Set Minimum"))
        self.clear_pushButton.setText(_translate("PlotHistoryWindow", "Clear History"))
        self.set_max_pushButton.setText(_translate("PlotHistoryWindow", "Set Maximum"))
        self.data_label.setText(_translate("PlotHistoryWindow", "0"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotHistoryWindow = QtWidgets.QMainWindow()
    ui = Ui_PlotHistoryWindow()
    ui.setupUi(PlotHistoryWindow)
    PlotHistoryWindow.show()
    sys.exit(app.exec_())
